version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexuspass
      POSTGRES_DB: nexusdb
    volumes:
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: ["5432:5432"]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]

  redis:
    image: redis:7

  bridge:
    build: ./bridge
    depends_on: [postgres, minio, redis]
    ports: ["8000:8000"]