apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: nexus-phase-a
spec:
  replicas: 1
  selector:
    matchLabels: { app: minio }
  template:
    metadata:
      labels: { app: minio }
    spec:
      containers:
      - name: minio
        image: minio/minio
        args: [ "server", "/data", "--console-address", ":9001" ]
        env:
        - { name: MINIO_ROOT_USER, value: minioadmin }
        - { name: MINIO_ROOT_PASSWORD, valueFrom: { secretKeyRef: { name: nexus-secret, key: miniopass } } }
        ports: [ { containerPort: 9000 }, { containerPort: 9001 } ]
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: nexus-phase-a
spec:
  ports:
  - { name: api, port: 9000 }
  - { name: console, port: 9001 }
  selector: { app: minio }
